### ISSUE TITLE
"Error while communicating with Riot Games API"

### ISSUE THREAD

**Issue by scv64** [GeorgeGee/league-summoner-name-checker#1]
I am using the program well.
However, this error message is displayed when searching for a large number of names.
"Error while communicating with Riot Games API"
I am getting this error message, what is the problem?

**Comment by GeorgeGee** [comment]
Hello @scv64,

1. Is there any more information displayed when the error occurs? The exception message should follow that error message.
2. How many names are you trying to check at once when the error occurs? If possible, a sample input file would help as I can try and reproduce the issue myself.

**Comment by scv64** [comment]
Thank you for answer.
Normally, this error occurs well when searching for more than 100 names at a time. And the error message is displayed after outputting the result until the error occurs.

**Comment by GeorgeGee** [comment]
Which server are you experiencing this issue for? I've been able to check several hundred names on `euw1` with no errors, but I have not tested large name lists on other servers.

If you're able to reproduce the issue, there should be more information following "Error while communicating with Riot Games API **...**" (in place of the bold ellipsis), which will help me work out what's going wrong. A screenshot of it happening might help.

**Comment by GeorgeGee** [comment]
Which server are you experiencing this issue for? I've been able to check several hundred names on `euw1` with no errors, but I have not tested large name lists on other servers.

If you're able to reproduce the issue, there should be more information following "Error while communicating with Riot Games API **...**" (in place of the ellipsis), which will help me work out what's going wrong. A screenshot of it happening might help.

**Comment by scv64** [comment]
Server is kr.
The search for the name you entered is not finished, and the corresponding message is printed, and the job ends. Below that, the search result of the name that has been successfully searched is displayed.

**Comment by scv64** [comment]
![image](https://user-images.githubusercontent.com/67246984/87617227-f54d8c80-c751-11ea-8fe6-ef95138ffbe8.png)

I get an error like screenshot

**Comment by GeorgeGee** [comment]
Thanks for providing the screenshot.

I have been able to reproduce the issue myself, and I have a working fix for it. I am just having a think about whether there is a better solution to the problem before I push it. I should have a fix pushed over the next couple of days.

**Comment by GeorgeGee** [comment]
@scv64 From the testing I've done it seems that the Riot Games API will sometimes return 503 Service Unavailable when making API requests for the Korean server, which was resulting in the scenario where a summoner was fetched but their match history was not, which the code did not properly handle. I have implemented a workaround to gracefully handle this scenario by ignoring the failed request and continuing through the list in commit b5048375725008e4689ddce5f97722648b158db4 which has been merged into master. I have also tagged a new release 1.2.2.

In the future I may consider retrying these failed requests, similar to when the rate limit is exceeded. For now, this should allow you to use the library without issues.

Thanks for reporting this. Let me know if you encounter any further issues.

**Comment by scv64** [comment]
I tested it now and it works fine. 
Thanks for the quick feedback.😊

**Comment by scv64** [comment]
I have additional questions. Is there a way to search for all the summoner names that exist on the server, not how to search for the summoner name in a txt list?

**Comment by GeorgeGee** [comment]
Unfortunately that is not possible. The Riot Games API does not have support for fetching a list of existing summoner names.
