### ISSUE TITLE
I've recently had a problem.

### ISSUE THREAD

**Issue by scv64** [GeorgeGee/league-summoner-name-checker#2]
I'm using the program well, but I've recently had a problem.
All search results come out as unknown
![1234](https://user-images.githubusercontent.com/67246984/148482463-609fe54e-c376-4403-9fca-df263898996e.png)

**Comment by Verdq** [comment]
any reply ?

**Comment by GeorgeGee** [comment]
This issue was caused by changes to endpoints in the Riot Games API.

I have just updated the library to resolve this. Please visit the releases page and download version 2.0.0. Note that the server code format has changed.
